version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bookit-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookit_db
      MYSQL_USER: bookit_user
      MYSQL_PASSWORD: my_pass_Vik
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: bookit-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookit_db
      SPRING_DATASOURCE_USERNAME: bookit_user
      SPRING_DATASOURCE_PASSWORD: my_pass_Vik
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mysql_data:
