spring.application.name=BookIt

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=root
logging.level.org.springframework.security=DEBUG
spring.app.jwtSecret=mySecretKeydjvbekvujbwgu42y98u3h1eujb2fcu4gh9t84h9f3dubce4238gfhc0
spring.app.jwtExpirationMs=172800000
spring.devtools.restart.enabled=false

frontend.url=https://bookit.fivestacks.in
logging.level.root=info

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB