spring.datasource.url=jdbc:mysql://localhost:3306/bookit_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=admin
spring.security.user.password=root
logging.level.org.springframework.security=DEBUG
logging.level.root=INFO

spring.app.jwtSecret=mySecretKey
spring.app.jwtExpirationMs=172800000

spring.devtools.restart.enabled=false
frontend.url=http://localhost:3000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_gmail_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
